name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "ParticleSeg 3D: dataset"
  comment: "The sample dataset consisting of the whole CT images and the patch dataset with extracted patches from these samples alongside their respective instance segmentations"
  url: "https://syncandshare.desy.de/index.php/s/wjiDQ49KangiPj5/download"
  file_name: "ParticleSeg3D.zip"
  piece_size: 24 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
