name: Pes2021
on:
  push:
    branches:
      - master
      
env:
  name: "PES2021"
  comment: "PES2021"
  url: "https://up.downloadcomputergames.net/2021/10/download-pes-2021-pc/eFootball-PES-2021.zip"
  file_name: "eFootball-PES-2021.zip"
  piece_size: "2^23"
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
