name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Shadow warrior 2"
  comment: "Shadow warrior 2 for pc"
  url: "https://datanodes.to/e9jl3qbjga1n/Shadow-Warrior_2.rar"
  file_name: "SW2-windows.exe"
  piece_size: 13.1 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
